"""
conftest.py — Fixture bersama untuk semua test.

Asumsi: Stack Docker Compose sudah berjalan (`docker compose up -d`)
sehingga aggregator dapat diakses di http://localhost:8080.

Test ini adalah BLACK-BOX / INTEGRATION TEST terhadap service yang
benar-benar berjalan di container, sesuai spesifikasi tugas yang
meminta bukti perilaku sistem nyata (idempotency, dedup, persistensi,
konkurensi) bukan hanya unit test terisolasi.
"""

import asyncio
import os
import uuid
from datetime import datetime, timezone

import httpx
import pytest
import pytest_asyncio

BASE_URL = os.environ.get("TEST_BASE_URL", "http://localhost:8080")


@pytest_asyncio.fixture
async def client():
    async with httpx.AsyncClient(base_url=BASE_URL, timeout=30.0) as c:
        yield c


def make_event(topic: str = "test-topic", event_id: str | None = None, source: str = "pytest") -> dict:
    return {
        "topic": topic,
        "event_id": event_id or str(uuid.uuid4()),
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "source": source,
        "payload": {"value": 42, "note": "generated by pytest"},
    }


@pytest.fixture
def event_factory():
    return make_event
